### ISSUE TITLE
Deploying link

### ISSUE THREAD

**Issue by jenadiusnicholaus** [jenadiusnicholaus/my_portifolio_site#15]
https://jenadiusnicholaus.github.io/my-portfolio-site/

**Comment by Hamzaoutdoors** [comment]
Hi @jenadiusnicholaus, 

## Congratulations! 🎉 Project Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀

To Highlight:

- [x] Project well-deployed using Github page

_Cheers and Happy coding and Keep rocking!_ 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jenadiusnicholaus** [comment]
Thanks @Hamzaoutdoors
